add 8-th homework
tuse4ka1984/-Python-1- pull request #12
Opened 2024-08-12 18:09 UTC by tuse4ka1984

2024-08-12 19:53 UTC, kristina71 requested changes

2024-08-12 19:53 UTC, kristina71 commented on lesson_8/employee.py
> + def create_company(self, name, description=""):
кажется на это должен быть свой класс - Company, так как это не относится к сотруднику

2024-08-12 19:53 UTC, kristina71 commented on lesson_8/employee.py
> + def edit(self, new_id, new_mail, new_active):
лучше назвать edit_company

2024-08-12 19:53 UTC, kristina71 commented on lesson_8/employee.py
> + def delete_company(self, id):
аналогично - переместить в класс компании

2024-08-12 19:53 UTC, kristina71 commented on lesson_8/test_employee.py
> +    id_com = new_id
лишняя операция. Можно сразу назвать переменную как нужно

2024-08-13 06:44 UTC, tuse4ka1984 commented on lesson_8/employee.py
> + def create_company(self, name, description=""):
Исправила

2024-08-13 06:46 UTC, tuse4ka1984 commented on lesson_8/employee.py
> + def edit(self, new_id, new_mail, new_active):
Исправила. Назвала edit_employee, т.к. это относится к сотрудникам

2024-08-13 06:46 UTC, tuse4ka1984 commented on lesson_8/employee.py
> + def delete_company(self, id):
Исправила

2024-08-13 06:47 UTC, tuse4ka1984 commented on lesson_8/employee.py
> + def edit(self, new_id, new_mail, new_active):
Случайно удалила один комментарий по поводу переменной. Тоже исправила

2024-08-13 07:05 UTC, closed without merging